Task12: FatUglyController
vagroz/Scala-complete-course pull request #13
Opened 2018-02-04 14:28 UTC by vagroz

2018-02-21 20:48 UTC, vatt2001 requested changes

2018-02-21 20:48 UTC, vatt2001 commented on src/main/scala/lectures/oop/myhttp/HttpHandlerMyImpl.scala
> +      }.getOrElse(Future.successful(HttpResponse(HttpStatusCodes.BadRequest, "Can not upload empty file")))
Мысли вслух (можно не править): Еще бы ошибки кидать из хэндлера как исключения, а уже потом их трансформировать в соответствующие HttpResponse.

2018-02-21 20:48 UTC, vatt2001 commented on src/main/scala/lectures/oop/myhttp/HttpHandlerMyImpl.scala
> +          Future.successful(HttpResponse(HttpStatusCodes.BadRequest, "File size should not be more than 8 MB"))
Согласен про вынос в конфиг MAX_FILE_SIZE, но тогда надо и в текст ошибки так же прокидывать.

2018-02-21 20:48 UTC, vatt2001 commented on src/main/scala/lectures/oop/myhttp/HttpHandlerMyImpl.scala
> +      val responseBuf = new StringBuilder()
Разбор боди и парсинг бодипартов на имя файла и содержимое так же стоит вынести в отдельные методы, они здесь только портят читаемость.

2018-02-21 20:48 UTC, vatt2001 commented on src/main/scala/lectures/oop/myservices/MailService.scala
> +  def sendMessageToIbmMq(message: String): String = {
Это работа с очередью, ей не место в MailService.

2018-03-11 10:29 UTC, vagroz commented on src/main/scala/lectures/oop/myservices/MailService.scala
> +  def sendMessageToIbmMq(message: String): String = {
действительно. Просто на тот момент я плохо представлял, что такое очередь)

2018-03-13 22:13 UTC, vatt2001 approved these changes

2018-03-13 22:13 UTC, merged