Task14
vagroz/Scala-complete-course pull request #16
Opened 2018-04-17 21:22 UTC by vagroz

2018-05-16 19:23 UTC, vatt2001 requested changes

2018-05-16 19:23 UTC, vatt2001 commented on src/test/scala/lectures/functions/AuthenticationTest.scala
> +    val badUserGenerator: Gen[User] = Gen.frequency(
Зачем тебе отдельные генераторы внутри тестов?
Если уж писать через генераторы и нет каких-то особых требований в тесте, имхо, проще и понятней написать по одному генератору для каждого типа авторизации, и внутри каждого такого генератора создавать все возможные виды входных данных данного типа.

2018-05-16 19:32 UTC, sergeypopov83 commented on src/main/scala/lectures/functions/Authentication.scala
> +  val auth = (user: User) => authByCard.lift(user) ++ authByLP.lift(user)
тогда уж authByCard.orElse(authByLP).lift(user)

2018-05-23 16:21 UTC, vatt2001 approved these changes

2018-05-23 16:22 UTC, merged