Task1
vagroz/Scala-complete-course pull request #2
Opened 2017-09-20 16:06 UTC by vagroz

Task1 complete

2017-09-20 16:11 UTC, vagroz commented
Почему в последней задаче logParameter[String] требовал обязательного наличия подчеркивания?

2017-09-20 20:02 UTC, vatt2001 commented
У подчеркивания есть несколько разных значений, в зависимости от контекста. И об этом мы еще будем говорить. В лекциях есть слайд об этом, там есть все его применения.

2017-09-20 20:27 UTC, vatt2001 requested changes

2017-09-20 20:27 UTC, vatt2001 commented on src/main/scala/lectures/functions/Computations.scala
> +  }
Можно ли здесь минимизировать количество разбиений строки filterData на отдельные слова?

2017-09-20 20:27 UTC, vatt2001 commented on src/main/scala/lectures/functions/SQLAPI.scala
> +
Закомменченный код коммитить не надо.

2017-09-21 17:44 UTC, vagroz commented on src/main/scala/lectures/functions/Computations.scala
> +  }
Мне кажется, что этот случай не отличается от предыдущих, и тут разбиение строки происходит 1 раз. Я не прав?
Единственное, что приходит на ум - вообще не разбивать строку, а смотреть включение dataItem в filterData

2017-09-21 20:05 UTC, vatt2001 commented on src/main/scala/lectures/functions/Computations.scala
> +  }
Здесь мы возвращаем функцию, которая на вход принимает dataArray и вычисляет то, что написано в теле (`filterData.split(" ").filter(dataItem => dataArray.contains (dataItem)`). При этом на каждый переданный dataArray мы будем вычислять все тело заново, делая лишнюю работу.

2017-09-22 11:37 UTC, vagroz commented on src/main/scala/lectures/functions/Computations.scala
> +  }
Можно определить это как функцию с помощью val (и, чтобы наверняка, в теле вынести filterData.split(" ") как отдельную переменную). Но тогда все будет плохо, если изменится строка filterData.

Я бы вообще хранил массив из filterData как глобальный, и апдейтил каждый раз после изменения строки.

2017-09-25 19:51 UTC, vatt2001 commented on src/main/scala/lectures/functions/Computations.scala
> +  }
Мы изучаем функциональное программирование. В нем ничего никогда не меняется, все иммутабельное :)
Поэтому не надо переживать за изменение входных данных. Наоборот, это правильно и хорошо, что `filterData` "фиксируется" в той функции, которая будет на выходе `functionalComputation`

2017-09-27 21:41 UTC, merged