Task2
vagroz/Scala-complete-course pull request #3
Opened 2017-09-29 16:00 UTC by vagroz

2017-10-04 19:03 UTC, sergeypopov83 commented on src/main/scala/lectures/functions/Authentication.scala
> +    user match {
authByCard и authByLP, это функции, которые тоже можно композировать, теми же способами, что и обычные функции.
В данной реализации ты проводишь паттерн мэтчинг лишний раз, можно обойтись только мэтчингом в функциях

2017-10-04 19:03 UTC, sergeypopov83 commented on src/main/scala/lectures/matching/SortingStuff.scala
> +    def findMyKnife(stuffBox: StuffBox): Boolean = stuffBox match {
а тут мэтчинг не нужен

2017-10-05 14:51 UTC, vatt2001 requested changes

2017-10-05 14:51 UTC, vatt2001 commented on src/main/scala/lectures/matching/SortingStuff.scala
> +  def sortJunk(stuff: List[Stuff]): StuffBox = sort(stuff, StuffBox()) ///sort(stuff, StuffBox())
комменты здесь лишние

2017-10-05 14:51 UTC, vatt2001 commented on src/main/scala/lectures/operators/Competition.scala
> +  }*/
Здесь тоже комменты ни к чему

2017-10-06 19:00 UTC, vagroz commented on src/main/scala/lectures/matching/SortingStuff.scala
> +    def findMyKnife(stuffBox: StuffBox): Boolean = stuffBox match {
странно, а в задании представлена именно такая форма. Если без мэтчинга, как получить доступ к полю junk?
Нельзя же так просто написать `stuffBox.junk.contains(knife)`.
На ум пришел только вариант с частичной функцией.

2017-10-12 20:17 UTC, merged

2017-10-12 20:24 UTC, sergeypopov83 commented on src/main/scala/lectures/functions/Authentication.scala
> -    }
val f = authByLP.orElse(authByLP2).lift
for (user <- testUsers) yield {
f (user)
}
так тебе не понадобится создавать инстансы лифтонутых функций каждый раз в теле цикла