Task3
vagroz/Scala-complete-course pull request #5
Opened 2017-10-08 14:05 UTC by vagroz

2017-10-12 20:47 UTC, vatt2001 requested changes

2017-10-12 20:47 UTC, vatt2001 commented on src/main/scala/lectures/collections/MergeSortImpl.scala
> +  def merge(left: Seq[Int], right: Seq[Int], res: Seq[Int] = Seq()): Seq[Int] = {
Да, так реализовать можно и оно даже будет неплохо работать.
А можешь написать через pattern matching? Может получиться гораздо наглядней.

2017-10-12 20:47 UTC, vatt2001 commented on src/main/scala/lectures/collections/MyListImpl.scala
> +          else List[Int]()
Обычно вместо `List()` наглядней писать `List.empty`

2017-10-12 20:47 UTC, vatt2001 commented on src/main/scala/lectures/functions/Fibonacci.scala
>      if (num == 1) 1
Здесь и ниже лучше сцепить все if-ы друг с другом

2017-10-12 20:47 UTC, vatt2001 commented on src/test/scala/lectures/functions/FibonacciTest.scala
> +  }
Здесь и далее:
Не надо в одном тесте группировать разные сценарии. Чем меньше скоуп одного теста, тем проще его поддерживать.

2017-10-12 20:47 UTC, vatt2001 commented on src/test/scala/lectures/functions/SQLAPITest.scala
> +  trait dialog {
Имя трейта всегда с большой буквы

2017-10-12 20:47 UTC, vatt2001 commented on src/test/scala/lectures/operators/CompetitionTest.scala
> +  "Associative massive" should "have form ('Artem vs John' -> 3)" in {
Перед should всегда ставится имя класса, которого ты собираешься тестировать

2017-10-18 21:17 UTC, vagroz commented on src/test/scala/lectures/operators/CompetitionTest.scala
> +  "Associative massive" should "have form ('Artem vs John' -> 3)" in {
Вот тут не понятно. В примерах скалатест перед should пишут сущность/объект, который тестируется, а имя класса указано в названии класса теста. Аналогично у меня в отделе пишут. Сергей тоже сказал, что ничего плохого в таком стиле нет...

2017-10-19 22:16 UTC, vatt2001 commented on src/test/scala/lectures/operators/CompetitionTest.scala
> +  "Associative massive" should "have form ('Artem vs John' -> 3)" in {
ОК, согласен, в доке написано так:

```
Each specification sentence has a "subject," which is sometimes called the system under test (or SUT). The subject is the entity being specified and tested and also serves as the subject of the sentences you write for each test
```

2017-10-19 22:18 UTC, vatt2001 approved these changes

2017-10-19 22:18 UTC, merged