Task5
vagroz/Scala-complete-course pull request #7
Opened 2017-10-29 20:58 UTC by vagroz

В toString использовал мутабельную очередь и переменные, потому что без них написание кода заняло бы в несколько раз больше времени...

2017-11-02 23:14 UTC, vatt2001 requested changes

2017-11-02 23:14 UTC, vatt2001 commented on src/main/scala/lectures/oop/BST.scala
> +      }
`leaf.flatMap(_.find(value))`

2017-11-02 23:14 UTC, vatt2001 commented on src/main/scala/lectures/oop/BST.scala
> +  private def emptyStr(n: Int, s: String = "."): String = (1 to n).map (_ => s).mkString("")
Все тело метода можно заменить на `s * n`

2017-11-02 23:14 UTC, vatt2001 commented on src/main/scala/lectures/oop/BST.scala
> +  override def toString(): String = {
Попробуй написать этот метод через рекурсивные вызовы toString у поддеревьев и потом объединение результата

2017-12-06 09:42 UTC, sergeypopov83 commented on src/main/scala/lectures/oop/BST.scala
> +      leaf.flatMap(_.find(value))
метод addInner - явно не часть интерфейса, соответвенно он должен быть скрыт от пользователей (pivate или protected)

2017-12-06 12:06 UTC, sergeypopov83 commented on src/main/scala/lectures/oop/BST.scala
>      val (curLevel, curPos) = getLevelPositionByNum(qNode.num)
private case class NodeInQueue(node: BSTImpl, num: Int) - надо сделать классно внутри компанион обжекта
Что бы не создавать каждый раз

2017-12-06 12:06 UTC, sergeypopov83 commented on src/main/scala/lectures/oop/BST.scala
>      val (curLevel, curPos) = getLevelPositionByNum(qNode.num)
Ты предполагаешь, что длинна ноды фиксированная. Я пропущу это доупущение, но, по заданию, это не так и каждая нода может иметь произвольную длинную

2017-12-06 12:06 UTC, merged